export const GET_NOTES_LIST = 'GET_NOTES_LIST';
export const GET_NOTE_ITEMS = 'GET_NOTE_ITEMS';
export const ADD_NOTE_ITEM = 'ADD_NOTE_ITEM';
export const DELETE_NOTE_ITEM = 'DELETE_NOTE_ITEM';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const SET_LOADING = '  SET_LOADING';
export const ADD_NOTE_CATEGORY = 'ADD_NOTE_CATEGORY';
export const SORT_NOTE_ITEMS = 'SORT_NOTE_ITEMS';
